default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  port: <%= ENV.fetch("DB_PORT") %>
  host: <%= ENV.fetch("DB_HOSTNAME") %>

development:
  <<: *default
  database: briefing_api_development

test:
  <<: *default
  database: briefing_api_test

production:
  primary: &primary_production
    <<: *default
    database: briefing_api_production
    username: briefing_api
    password: <%= ENV["BRIEFING_API_DATABASE_PASSWORD"] %>
#  cache:
#    <<: *primary_production
#    database: briefing_api_production_cache
#    migrations_paths: db/cache_migrate
#  queue:
#    <<: *primary_production
#    database: briefing_api_production_queue
#    migrations_paths: db/queue_migrate
#  cable:
#    <<: *primary_production
#    database: briefing_api_production_cable
#    migrations_paths: db/cable_migrate
